name: IT academy Homework 11

on: 
  push:
  workflow_dispatch:
jobs:
  itacad_hw-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Convert variable to lowercase
        run: repository_owner_lowercase=${{ github.repository_owner }}
      - run: echo "${repository_owner_lowercase}"
#       - name: Build WCG Docker image
#         run: docker build -t ghcr.io/${repository_owner_lowercase}/wcg:${{ github.sha }} -t ghcr.io/${repository_owner_lowercase}/wcg:latest -f Dockerfile.multi .
#       - name: Publish WCG Docker image
#         run: |
#           docker push ghcr.io/${repository_owner_lowercase}/wcg:${{ github.sha }}
#           docker push ghcr.io/${repository_owner_lowercase}/wcg:latest
